#!/bin/bash

export OPENJFX_JMODS_HOME="/Users/ekko/Documents/javafx-jmods-21.0.11"

cd ../../

if [ -n "$1" ] && [ "$1" != "-Dmvn" ]; then
  mvn clean install
fi

[ -e 'build' ] && rm -rf build

jlink \
  --module-path $JAVA_HOME/jmods:$OPENJFX_JMODS_HOME \
  --add-modules javafx.controls,javafx.web,javafx.fxml,javafx.graphics,java.sql,java.naming,jdk.crypto.ec \
  --output build/runtime

jpackage \
  --runtime-image build/runtime \
  --type dmg \
  --name 'Valkyrie DB' \
  --input launcher/target \
  --main-jar launcher-v1.0.0-arch.1.jar \
  --main-class "valkyrie.Launcher" \
  --java-options "-Dprism.order=sw -Dprism.verbose=true" \
  --dest build